tap "dart-lang/dart"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/services"
tap "romkatv/powerlevel10k"
tap "sass/sass"
tap "shivammathur/php"
tap "smartthingscommunity/smartthings"
# Cryptography and SSL/TLS Toolkit
brew "openssl@3"
# Cross-platform make
brew "cmake"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# General-purpose scripting language
brew "php", link: false
# Dependency Manager for PHP
brew "composer"
# Good-lookin' diffs with diff-highlight and more
brew "diff-so-fancy"
# Isolated development environments using Docker
brew "docker-compose"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Open-source GitLab command-line tool
brew "glab"
# Apache HTTP server
brew "httpd", restart_service: true
# Lightweight and flexible command-line JSON processor
brew "jq"
# Mac App Store command-line interface
brew "mas"
# Theme for zsh
brew "powerlevel10k"
# Install various Ruby versions and implementations
brew "ruby-build"
# Ruby version manager
brew "rbenv"
# Programmatically correct mistyped console commands
brew "thefuck"
# Simplified and community-driven man pages
brew "tldr"
# Language for application scale JavaScript development
brew "typescript"
# Vi 'workalike' with many additional features
brew "vim"
# Real-time type-ahead completion for Zsh
brew "zsh-autocomplete"
# Stylesheet Preprocessor
brew "sass/sass/sass"
# General-purpose scripting language
brew "shivammathur/php/php", link: false
# General-purpose scripting language
brew "shivammathur/php/php@8.0", link: true
# General-purpose scripting language
brew "shivammathur/php/php@8.1"
# General-purpose scripting language
brew "shivammathur/php/php@8.2"
# General-purpose scripting language
brew "shivammathur/php/php@8.4"
# View, print, and comment on PDF documents
cask "adobe-acrobat-reader"
# Collection of apps and services for photography, design, video, web, and UX
cask "adobe-creative-cloud"
# Menu bar icon organiser
cask "bartender"
# App to build and share containerised applications and microservices
cask "docker"
# Web browser
cask "firefox-developer-edition"
# Developer targeted fonts with a high number of glyphs
cask "font-fira-code-nerd-font"
# Developer targeted fonts with a high number of glyphs
cask "font-meslo-lg-nerd-font"
# Client for the Google Drive storage service
cask "google-drive"
# Terminal built on web technologies
cask "hyper"
# HTTP and GraphQL Client
cask "insomnia"
# Software for Logitech devices
cask "logitech-options"
# Shows the next meeting in the menu bar
cask "meetingbar"
# Monitors computer mic and webcam
cask "oversight"
# Protect your personal files
cask "ransomwhere"
# Window snapping tool
cask "rectangle-pro"
# Personal online hard drive to store, view and share files
cask "stack"
# System monitor for the menu bar
cask "stats"
# Customizable email client
cask "thunderbird"
# Automatic time and productivity tracking app
cask "timing"
# Free and open-source OpenVPN client
cask "tunnelblick"
# Open-source code editor
cask "visual-studio-code"
# Native desktop client for WhatsApp
cask "whatsapp"
mas "1Password for Safari", id: 1569813296
mas "AdBlock Pro", id: 1018301773
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Structured", id: 1499198946
vscode "bradlc.vscode-tailwindcss"
vscode "christian-kohler.npm-intellisense"
vscode "christian-kohler.path-intellisense"
vscode "codezombiech.gitignore"
vscode "davidanson.vscode-markdownlint"
vscode "dbaeumer.vscode-eslint"
vscode "eamodio.gitlens"
vscode "editorconfig.editorconfig"
vscode "esbenp.prettier-vscode"
vscode "heybourn.headwind"
vscode "humao.rest-client"
vscode "meganrogge.template-string-converter"
vscode "mhutchie.git-graph"
vscode "mrmlnc.vscode-duplicate"
vscode "pflannery.vscode-versionlens"
vscode "redhat.vscode-yaml"
vscode "ritwickdey.liveserver"
vscode "sidneys1.gitconfig"
vscode "stackbreak.comment-divider"
vscode "ultram4rine.vscode-choosealicense"
vscode "vitest.explorer"
vscode "vscode-icons-team.vscode-icons"
vscode "wix.vscode-import-cost"
vscode "yzhang.markdown-all-in-one"
