tap "homebrew/bundle"
tap "homebrew/services"
tap "nikitabobko/tap"
tap "shivammathur/php"
# Cryptography and SSL/TLS Toolkit
brew "openssl@3"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Good-lookin' diffs with diff-highlight and more
brew "diff-so-fancy"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Open-source GitLab command-line tool
brew "glab"
# Improved top (interactive process viewer)
brew "htop"
# C/C++ and Java libraries for Unicode and globalization
brew "icu4c@76"
# Mac App Store command-line interface
brew "mas"
# Port scanning utility for large networks
brew "nmap"
# Package compiler and linker metadata toolkit
brew "pkgconf"
# Python interface to Tcl/Tk
brew "python-tk@3.13"
# Cross-shell prompt for astronauts
brew "starship"
# User interface to the TELNET protocol
brew "telnet"
# Programmatically correct mistyped console commands
brew "thefuck"
# Simplified and community-driven man pages
brew "tldr"
# Terminal multiplexer
brew "tmux"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Language for application scale JavaScript development
brew "typescript"
# Real-time type-ahead completion for Zsh
brew "zsh-autocomplete"
# Password manager that keeps all passwords secure behind one password
cask "1password"
# Command-line interface for 1Password
cask "1password-cli"
# App to build and share containerised applications and microservices
cask "docker"
# Cross-platform Text Expander written in Rust
cask "espanso"
# Web browser
cask "firefox"
cask "font-fira-code-nerd-font"
cask "font-meslo-lg-nerd-font"
# Terminal emulator that uses platform-native UI and GPU acceleration
cask "ghostty"
# Git client focusing on productivity
cask "gitkraken"
# Web browser
cask "google-chrome"
# Menu bar manager
cask "jordanbaird-ice"
# Free cross-platform office suite, fresh version
cask "libreoffice"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Monitors computer mic and webcam
cask "oversight"
# Window snapping tool
cask "rectangle-pro"
# Personal online hard drive to store, view and share files
cask "stack"
# System monitor for the menu bar
cask "stats"
# Video game digital distribution service
cask "steam"
# Customizable email client
cask "thunderbird"
# Open-source code editor
cask "visual-studio-code"
# Multimedia player
cask "vlc"
mas "1Password for Safari", id: 1569813296
mas "AdBlock Pro", id: 1018301773
mas "AdGuard for Safari", id: 1440147259
vscode "azemoh.one-monokai"
vscode "biomejs.biome"
vscode "bradlc.vscode-tailwindcss"
vscode "christian-kohler.npm-intellisense"
vscode "christian-kohler.path-intellisense"
vscode "codezombiech.gitignore"
vscode "davidanson.vscode-markdownlint"
vscode "dbaeumer.vscode-eslint"
vscode "editorconfig.editorconfig"
vscode "esbenp.prettier-vscode"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "heybourn.headwind"
vscode "humao.rest-client"
vscode "meganrogge.template-string-converter"
vscode "mhutchie.git-graph"
vscode "mrmlnc.vscode-duplicate"
vscode "ms-azuretools.vscode-docker"
vscode "pflannery.vscode-versionlens"
vscode "redhat.vscode-yaml"
vscode "ritwickdey.liveserver"
vscode "sidneys1.gitconfig"
vscode "stackbreak.comment-divider"
vscode "tamasfe.even-better-toml"
vscode "ultram4rine.vscode-choosealicense"
vscode "vitest.explorer"
vscode "vscode-icons-team.vscode-icons"
vscode "wix.vscode-import-cost"
vscode "yzhang.markdown-all-in-one"
