tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "romkatv/powerlevel10k"
# Isolated development environments using Docker
brew "docker-compose"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Mac App Store command-line interface
brew "mas"
# Platform built on V8 to build network applications
brew "node@18"
# Programmatically correct mistyped console commands
brew "thefuck"
# Simplified and community-driven man pages
brew "tldr"
# Language for application scale JavaScript development
brew "typescript"
# A Zsh Theme
brew "romkatv/powerlevel10k/powerlevel10k"
# Password manager that keeps all passwords secure behind one password
cask "1password"
# View, print, and comment on PDF documents
cask "adobe-acrobat-reader"
# Menu bar icon organizer
cask "bartender"
# App to build and share containerized applications and microservices
cask "docker"
# Web browser
cask "firefox-developer-edition"
# Developer targeted fonts with a high number of glyphs
cask "font-meslo-lg-nerd-font"
# Web browser
cask "google-chrome"
# Terminal built on web technologies
cask "hyper"
# Shows the next meeting in the menu bar
cask "meetingbar"
# Provides updates to various Microsoft products
cask "microsoft-auto-update"
# Office suite
cask "microsoft-office"
# Meet, chat, call, and collaborate in just one place
cask "microsoft-teams"
# Protect your personal files
cask "ransomwhere"
# Control your tools with a few keystrokes
cask "raycast"
# Window snapping tool
cask "rectangle-pro"
# System monitor for the menu bar
cask "stats"
# Messaging app with a focus on speed and security
cask "telegram"
# Customizable email client
cask "thunderbird"
# Open-source code editor
cask "visual-studio-code"
mas "1Password for Safari", id: 1569813296
mas "AdBlock Pro", id: 1018301773
