alias _="sudo"
alias f="fuck"
alias c="clear"
alias help="tldr"
alias rmrf="rm -rf"
alias allow="sudo chmod +x"
alias path="tr ':' '\n' <<< "'$PATH'""
alias get-broken-links="find . -type l ! -exec test -e {} \; -print"
alias mac:up='maintenance -rp $HOME/Documents/personal/personal-coding-projects/dotfiles/brew'
